

ipo4xcmsSet = function(directory, parametersOutput, listArguments, N=4) {
    
    files = list.files(directory, recursive=T)
    
    #random selection of N files for IPO in each class
    classes<-unique(basename(dirname(files)))
    randfiles<-NULL
    for (i in 1:length(classes)){
       randfiles<-c(randfiles,sample(files[grep(classes[i], files)],N))
    }


    mzmlfile<-randfiles
    paramsPP <- getDefaultXcmsSetStartingParams() #load default parameters of IPO

    #user defined new parameters
    paramsPP$ppm <- listArguments[["ppm"]]
    paramsPP$min_peakwidth <- listArguments[["min_peakwidth"]]
    paramsPP$max_peakwidth <- listArguments[["max_peakwidth"]]

    #paramsPP$profparam <- list(step=0.005) #not yet used by IPO have to think of it for futur improvement
    resultPPpos <- optimizeXcmsSet(mzmlfile, paramsPP, subdir="IPO_results") #some images generated by IPO
    write.table(resultPPpos$best_settings$parameters, file=parametersOutput, sep="\t",row.names=FALSE) #can be read by user

}
